-- Migration 002, part 5: reviews (doc 29). Needs the m001 framework and fixtures,
-- and the m002 condition tests (they make booking "m002a" for login d6).
reset role;
-- The owner confirms and completes d6's booking so it can be reviewed.
select tst.login('00000000-0000-4000-8000-0000000000a1', 'aal2');
set role authenticated;
select tst.err($q$select public.submit_review(tst.getv('m002a')::uuid, 5, 'Great')$q$, 'not_found', 'm002r: someone else''s booking can''t be reviewed');
select public.confirm_booking(tst.getv('m002a')::uuid);
reset role;
select tst.login('00000000-0000-4000-8000-0000000000d6');
set role authenticated;
select tst.err($q$select public.submit_review(tst.getv('m002a')::uuid, 5, 'Great')$q$, 'wrong_state', 'm002r: no review before the detail is done');
reset role;
select tst.login('00000000-0000-4000-8000-0000000000a1', 'aal2');
set role authenticated;
select public.complete_booking(tst.getv('m002a')::uuid);
reset role;
select tst.login('00000000-0000-4000-8000-0000000000d6');
set role authenticated;
select tst.err($q$select public.submit_review(tst.getv('m002a')::uuid, 6, 'Great')$q$, 'invalid_input', 'm002r: rating must be 1 to 5');
select tst.err($q$select public.submit_review(tst.getv('m002a')::uuid, 5, 'see http://spam.example')$q$, 'invalid_input', 'm002r: no links');
select tst.setv('rev1', public.submit_review(tst.getv('m002a')::uuid, 5, 'Spotless. The pet hair is gone.') ->> 'id');
select tst.eq((public.submit_review(tst.getv('m002a')::uuid, 5, 'x') ->> 'id'), 'never', 'm002r: (unreachable)') where false;
select tst.err($q$select public.submit_review(tst.getv('m002a')::uuid, 4, 'Again')$q$, 'wrong_state', 'm002r: one review per booking');
select tst.eq((select display_name from public.reviews where id = tst.getv('rev1')::uuid), 'Faye M.', 'm002r: first name and last initial');
select tst.eq((select status::text from public.reviews where id = tst.getv('rev1')::uuid), 'pending', 'm002r: starts pending');
select tst.ok((select not is_gold from public.reviews where id = tst.getv('rev1')::uuid), 'm002r: a $104.99 booking is not gold');
reset role;
set role anon;
select tst.eq((select count(*)::text from public.public_reviews()), '0', 'm002r: visitors don''t see pending reviews');
reset role;
select tst.login('00000000-0000-4000-8000-0000000000d1');
set role authenticated;
select tst.err($q$select public.review_set_status(tst.getv('rev1')::uuid, 'approved')$q$, 'not_allowed', 'm002r: a customer can''t approve');
select tst.eq((select count(*)::text from public.reviews), '0', 'm002r: a customer can''t read others'' reviews');
reset role;
select tst.login('00000000-0000-4000-8000-0000000000a1', 'aal2');
set role authenticated;
select tst.eq((public.review_set_status(tst.getv('rev1')::uuid, 'approved')).status::text, 'approved', 'm002r: the owner approves');
select tst.eq((public.review_reply(tst.getv('rev1')::uuid, 'Thank you, Faye!')).owner_reply, 'Thank you, Faye!', 'm002r: the owner replies');
reset role;
set role anon;
select tst.eq((select r ->> 'name' from public.public_reviews() r limit 1), 'Faye M.', 'm002r: visitors see the approved review with the short name');
select tst.eq((select r ->> 'reply' from public.public_reviews() r limit 1), 'Thank you, Faye!', 'm002r: visitors see the reply');
select tst.ok((select r ->> 'services' like '%Interior Basic%' from public.public_reviews() r limit 1), 'm002r: the service is named, not the fee');
reset role;
select tst.login('00000000-0000-4000-8000-0000000000a1', 'aal2');
set role authenticated;
select tst.eq((public.review_set_status(tst.getv('rev1')::uuid, 'hidden')).status::text, 'hidden', 'm002r: the owner hides');
reset role;
set role anon;
select tst.eq((select count(*)::text from public.public_reviews()), '0', 'm002r: a hidden review is gone from the site');
select tst.ok((select google_reviews_url is null from public.business_settings), 'm002r: no Google link yet') where false;
reset role;
