-- Migration 003: the owner's weekly hours (his answer of Oct 5 2026).
--   Open 10 AM to 7 PM every day (the hours already in business_settings), but:
--   * Monday to Thursday: not available 4 PM to 8 PM.
--   * Friday: not available 12 PM to 5 PM (Jummah prayer).
-- These repeat every week, unlike blocked_days (one-off closed days). A start
-- time is open only when the whole job finishes before a closure begins and
-- starts after it ends. open_starts is the single source of truth for open
-- times, so the calendar, the time list and every booking path follow it.
-- The admin can change the rows (same access as closed days).

create table public.weekly_closures (
  id int generated by default as identity primary key,
  weekday int not null check (weekday between 1 and 7),       -- ISO: 1 = Monday ... 7 = Sunday
  start_min int not null check (start_min between 0 and 1440), -- minutes after midnight
  end_min int not null check (end_min between 0 and 1440),
  reason text check (reason is null or char_length(reason) <= 200),
  created_at timestamptz not null default now(),
  constraint weekly_closures_window_ok check (start_min < end_min)
);
comment on table public.weekly_closures is
  'Hours closed every week (weekday 1 = Monday). No job may overlap one. The reason is visible to staff only.';

insert into public.weekly_closures (weekday, start_min, end_min, reason) values
  (1, 960, 1200, 'Not available 4 to 8 PM'),
  (2, 960, 1200, 'Not available 4 to 8 PM'),
  (3, 960, 1200, 'Not available 4 to 8 PM'),
  (4, 960, 1200, 'Not available 4 to 8 PM'),
  (5, 720, 1020, 'Jummah prayer');

-- Access: managers read, the admin edits (as for closed days).
grant select, insert, update, delete on public.weekly_closures to authenticated;
grant usage, select on sequence public.weekly_closures_id_seq to authenticated;
alter table public.weekly_closures enable row level security;
create policy "Managers: read weekly closures" on public.weekly_closures
  for select to authenticated using ((select public.is_manager()));
create policy "Admin: add weekly closures" on public.weekly_closures
  for insert to authenticated with check ((select public.is_admin()));
create policy "Admin: edit weekly closures" on public.weekly_closures
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admin: remove weekly closures" on public.weekly_closures
  for delete to authenticated using ((select public.is_admin()));

-- Open start times now skip the weekly closures (otherwise unchanged from Migration 001).
create or replace function public.open_starts(p_from date, p_days int, p_duration int, p_loc public.location_type,
                                              p_exclude uuid default null, p_staff boolean default false)
returns table (day date, start_min int)
language sql stable security definer set search_path = ''
as $$
  with st as (
    select s.*,
           (now() at time zone s.timezone)::date as today,
           (extract(hour from now() at time zone s.timezone) * 60
            + extract(minute from now() at time zone s.timezone))::int as minute_now,
           case when p_loc = 'mobile' then s.max_mobile_jobs else s.max_shop_jobs end as cap,
           case when p_loc = 'mobile' then s.mobile_buffer_min else s.shop_buffer_min end as own_buffer,
           least(greatest(coalesce(p_days, 1), 1), 62) as n_days
    from public.business_settings s
    where s.id = 1
  ),
  days as (
    select (p_from + g)::date as day
    from st, generate_series(0, st.n_days - 1) as g
    where p_from is not null and p_loc is not null and p_duration between 5 and 720
  ),
  cand as (
    select d.day, m as start_min, m + p_duration + st.own_buffer as c_end
    from st
    cross join days d
    cross join lateral generate_series(st.first_start_min, st.last_start_min, st.slot_step_min) as m
    where m + p_duration <= st.latest_end_min
      and (d.day > st.today or (d.day = st.today and m > st.minute_now))
      and (p_staff or d.day between st.today + st.min_days_ahead and st.today + st.max_days_ahead)
      and not exists (select 1 from public.blocked_days b where b.day = d.day)
      -- Migration 003: the job must not overlap an hour closed every week.
      and not exists (select 1 from public.weekly_closures w
                      where w.weekday = extract(isodow from d.day)::int
                        and m < w.end_min and m + p_duration > w.start_min)
  ),
  busy as (
    select a.service_date, a.start_min, a.location_type,
           a.end_min + case when a.location_type = 'mobile' then st.mobile_buffer_min else st.shop_buffer_min end as b_end
    from st
    join public.appointments a
      on a.service_date >= p_from and a.service_date < p_from + st.n_days
    where a.id is distinct from p_exclude
      and public.holds_time(a.status, a.queue, a.hold_expires_at)
  )
  select c.day, c.start_min
  from cand c
  cross join st
  where not exists (
    select 1
    from (select c.start_min as t
          union
          select b.start_min
          from busy b
          where b.service_date = c.day and b.start_min > c.start_min and b.start_min < c.c_end) as pts
    where (select count(*) from busy b
           where b.service_date = c.day and b.location_type = p_loc
             and b.start_min <= pts.t and b.b_end > pts.t) >= st.cap
       or (not st.shop_and_mobile_together
           and exists (select 1 from busy b
                       where b.service_date = c.day and b.location_type <> p_loc
                         and b.start_min <= pts.t and b.b_end > pts.t)))
  order by c.day, c.start_min
$$;

-- The site can show the weekly hours: the closures ride along with the public settings.
create or replace function public.get_public_settings() returns jsonb
language sql stable security definer set search_path = ''
as $$
  select jsonb_build_object(
    'timezone', s.timezone,
    'first_start_min', s.first_start_min,
    'last_start_min', s.last_start_min,
    'latest_end_min', s.latest_end_min,
    'slot_step_min', s.slot_step_min,
    'min_days_ahead', s.min_days_ahead,
    'max_days_ahead', s.max_days_ahead,
    'hold_hours', s.hold_hours,
    'public_phone', s.public_phone,
    'public_area', s.public_area,
    'mobile_radius_miles', s.mobile_radius_miles,
    'mobile_note', s.mobile_note,
    'customer_notice', s.customer_notice,
    'google_reviews_url', s.google_reviews_url,
    'weekly_closures', (select coalesce(jsonb_agg(jsonb_build_object('weekday', w.weekday, 'start_min', w.start_min, 'end_min', w.end_min)
                                                  order by w.weekday, w.start_min), '[]'::jsonb)
                        from public.weekly_closures w))
  from public.business_settings s
  where s.id = 1
$$;
